name: macOS-x86_64

on: [push, pull_request]

jobs:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: dependencies
    - name: cmake build
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
    - name: cmake make
      run: cmake --build build --parallel 3
    - name: test
      run: ./build/test/jsonrpcpp_test
