name: Ubuntu-amd64

on: [push, pull_request]

jobs:

  linux:

    strategy:
      fail-fast: false
      matrix:
        compiler:
          - clang-10
          - clang-11
          - clang-12
          - clang-13
          - clang-14
          - clang-15
          - clang-16
          - clang-17
          - clang-18
          - gcc-9
          - gcc-10
          - gcc-11
          - gcc-12
          - gcc-13
          - gcc-14
        include:
          - compiler: clang-10
            cc: clang-10
            cxx: clang++-10
            os: ubuntu-20.04
          - compiler: clang-11
            cc: clang-11
            cxx: clang++-11
            os: ubuntu-20.04
          - compiler: clang-12
            cc: clang-12
            cxx: clang++-12
            os: ubuntu-20.04
          - compiler: clang-13
            cc: clang-13
            cxx: clang++-13
            os: ubuntu-22.04
          - compiler: clang-14
            cc: clang-14
            cxx: clang++-14
            os: ubuntu-22.04
          - compiler: clang-15
            cc: clang-15
            cxx: clang++-15
            os: ubuntu-22.04
          - compiler: clang-16
            cc: clang-16
            cxx: clang++-16
            os: ubuntu-24.04
          - compiler: clang-17
            cc: clang-17
            cxx: clang++-17
            os: ubuntu-24.04
          - compiler: clang-18
            cc: clang-18
            cxx: clang++-18
            os: ubuntu-24.04
          - compiler: gcc-9
            cc: gcc-9
            cxx: g++-9
            os: ubuntu-22.04
          - compiler: gcc-10
            cc: gcc-10
            cxx: g++-10
            os: ubuntu-22.04
          - compiler: gcc-11
            cc: gcc-11
            cxx: g++-11
            os: ubuntu-22.04
          - compiler: gcc-12
            cc: gcc-12
            cxx: g++-12
            os: ubuntu-22.04
          - compiler: gcc-13
            cc: gcc-13
            cxx: g++-13
            os: ubuntu-24.04
          - compiler: gcc-14
            cc: gcc-14
            cxx: g++-14
            os: ubuntu-24.04

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: print environment
        run: env
      - name: configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
      - name: build
        run: cmake --build build --parallel 3
        env:
          CC: ${{ matrix.cc }}
          CXX: ${{ matrix.cxx }}
      - name: test
        run: ./build/test/jsonrpcpp_test

  macos:

    strategy:
      fail-fast: false
      matrix:
        xcode:
          - "13.1"
          - "13.2"
          - "13.3"
          - "13.4"
          - "14.0"
          - "14.1"
          - "14.2"
          - "14.3"
          - "15.0"
          - "15.1"
          - "15.2"
          - "15.3"
          - "15.4"
        include:
          - xcode: "13.1"
            os: macos-12
          - xcode: "13.2"
            os: macos-12
          - xcode: "13.3"
            os: macos-12
          - xcode: "13.4"
            os: macos-12
          - xcode: "14.0"
            os: macos-12
          - xcode: "14.1"
            os: macos-13
          - xcode: "14.2"
            os: macos-13
          - xcode: "14.3"
            os: macos-14
          - xcode: "15.0"
            os: macos-14
          - xcode: "15.1"
            os: macos-14
          - xcode: "15.2"
            os: macos-14
          - xcode: "15.3"
            os: macos-14
          - xcode: "15.4"
            os: macos-14

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: print environment
        run: env
      - name: configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
        env:
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
      - name: build
        run: cmake --build build --parallel 3 --verbose
      - name: test
        run: ./build/test/jsonrpcpp_test


  windows:

    strategy:
      fail-fast: false
      matrix:
        compiler:
          - vs-16
          - vs-17
        include:
          - compiler: vs-16
            os: windows-2019
            vs: "Visual Studio 16 2019"
          - compiler: vs-17
            os: windows-2022
            vs: "Visual Studio 17 2022"

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: configure
        run: |
          echo vcpkg installation root: ${env:VCPKG_INSTALLATION_ROOT}
          cmake -S . -B build -G "${{ matrix.vs }}" `
            -DWERROR=ON `
            -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake" `
            -DVCPKG_TARGET_TRIPLET="x64-windows" `
            -DCMAKE_BUILD_TYPE=Release `"
      - name: build
        run: cmake --build build --config Release --parallel 3 --verbose
      - name: test
        run: .\build\test\jsonrpcpp_test.exe
